services:

  postgres:
    image: postgres:15-alpine

    container_name: spa_postgres

    environment:
      POSTGRES_USER: spa_user
      POSTGRES_PASSWORD: spa_password
      POSTGRES_DB: spa_mgmt_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  postgres_data:

