import { Service, Product, Therapist, Review, Promotion, Appointment } from '@/types';

export const services: Service[] = [
  {
    id: 'sv1',
    name: 'Massage Thư Giãn Toàn Thân',
    description: 'Liệu pháp massage toàn thân giúp thư giãn cơ bắp, giảm căng thẳng và cải thiện tuần hoàn máu với tinh dầu thiên nhiên cao cấp.',
    price: 450000,
    duration: 90,
    category: 'Massage',
    image: 'https://picsum.photos/seed/spa1/600/400',
    rating: 4.8,
    reviewCount: 128,
    benefits: ['Giảm căng thẳng', 'Thư giãn cơ bắp', 'Cải thiện tuần hoàn', 'Tăng cường năng lượng'],
    therapists: ['th1', 'th2', 'th3'],
  },
  {
    id: 'sv2',
    name: 'Chăm Sóc Da Mặt Cơ Bản',
    description: 'Dịch vụ chăm sóc da mặt toàn diện với quy trình làm sạch, tẩy tế bào chết, đắp mặt nạ và dưỡng ẩm chuyên sâu.',
    price: 350000,
    duration: 60,
    category: 'Chăm Sóc Da',
    image: 'https://picsum.photos/seed/spa2/600/400',
    rating: 4.7,
    reviewCount: 95,
    benefits: ['Làm sạch sâu', 'Dưỡng ẩm tối ưu', 'Sáng da tức thì', 'Làm mịn da'],
    therapists: ['th2', 'th5'],
  },
  {
    id: 'sv3',
    name: 'Tắm Dưỡng Trắng Da',
    description: 'Liệu trình tắm dưỡng trắng da cao cấp kết hợp sữa tươi, mật ong và tinh chất vitamin C giúp da trắng sáng, mịn màng.',
    price: 600000,
    duration: 120,
    category: 'Chăm Sóc Cơ Thể',
    image: 'https://picsum.photos/seed/spa3/600/400',
    rating: 4.9,
    reviewCount: 72,
    benefits: ['Trắng da tự nhiên', 'Dưỡng ẩm sâu', 'Mịn màng tức thì', 'Chống lão hóa'],
    therapists: ['th6', 'th1'],
  },
  {
    id: 'sv4',
    name: 'Massage Đá Nóng',
    description: 'Liệu pháp massage với đá bazan núi lửa được nung nóng giúp thư giãn cơ sâu, giải tỏa căng thẳng và cân bằng năng lượng cơ thể.',
    price: 550000,
    duration: 90,
    category: 'Massage',
    image: 'https://picsum.photos/seed/spa4/600/400',
    rating: 4.9,
    reviewCount: 84,
    benefits: ['Thư giãn cơ sâu', 'Giảm đau nhức', 'Cân bằng năng lượng', 'Cải thiện giấc ngủ'],
    therapists: ['th3', 'th1'],
  },
  {
    id: 'sv5',
    name: 'Chăm Sóc Da Mặt Chuyên Sâu',
    description: 'Liệu trình chăm sóc da chuyên sâu với công nghệ tiên tiến, sử dụng serum collagen và peptide cao cấp giúp trẻ hóa làn da hiệu quả.',
    price: 750000,
    duration: 90,
    category: 'Chăm Sóc Da',
    image: 'https://picsum.photos/seed/spa5/600/400',
    rating: 4.8,
    reviewCount: 61,
    benefits: ['Trẻ hóa da', 'Giảm nếp nhăn', 'Tăng đàn hồi', 'Căng mịn tức thì'],
    therapists: ['th2', 'th5'],
  },
  {
    id: 'sv6',
    name: 'Massage Thái Cổ Truyền',
    description: 'Kỹ thuật massage Thái truyền thống kết hợp bấm huyệt và kéo giãn cơ giúp tăng độ linh hoạt, giảm đau và phục hồi năng lượng.',
    price: 500000,
    duration: 90,
    category: 'Massage',
    image: 'https://picsum.photos/seed/spa6/600/400',
    rating: 4.7,
    reviewCount: 103,
    benefits: ['Tăng linh hoạt', 'Giảm đau lưng', 'Phục hồi năng lượng', 'Cân bằng cơ thể'],
    therapists: ['th4', 'th1'],
  },
  {
    id: 'sv7',
    name: 'Waxing Toàn Thân',
    description: 'Dịch vụ waxing chuyên nghiệp sử dụng sáp tẩy lông cao cấp, nhẹ nhàng và hiệu quả, để lại làn da mịn màng hoàn hảo.',
    price: 400000,
    duration: 60,
    category: 'Làm Đẹp',
    image: 'https://picsum.photos/seed/spa7/600/400',
    rating: 4.6,
    reviewCount: 89,
    benefits: ['Loại bỏ lông triệt để', 'Da mịn màng', 'Hiệu quả lâu dài', 'Không đau'],
    therapists: ['th6', 'th2'],
  },
  {
    id: 'sv8',
    name: 'Facial Trẻ Hóa Da',
    description: 'Liệu trình facial cao cấp kết hợp công nghệ RF và siêu âm giúp nâng cơ, làm căng da và xóa mờ nếp nhăn hiệu quả.',
    price: 850000,
    duration: 75,
    category: 'Chăm Sóc Da',
    image: 'https://picsum.photos/seed/spa8/600/400',
    rating: 4.9,
    reviewCount: 47,
    benefits: ['Nâng cơ mặt', 'Xóa nếp nhăn', 'Căng da tức thì', 'Tươi trẻ lâu dài'],
    therapists: ['th5', 'th2'],
  },
  {
    id: 'sv9',
    name: 'Massage Bàn Chân Phản Xạ',
    description: 'Liệu pháp massage bàn chân theo phương pháp phản xạ học, tác động lên các huyệt đạo giúp cân bằng nội tạng và phục hồi sức khỏe.',
    price: 280000,
    duration: 45,
    category: 'Massage',
    image: 'https://picsum.photos/seed/spa9/600/400',
    rating: 4.7,
    reviewCount: 156,
    benefits: ['Cân bằng nội tạng', 'Giảm mệt mỏi', 'Cải thiện giấc ngủ', 'Tăng tuần hoàn'],
    therapists: ['th8', 'th4'],
  },
  {
    id: 'sv10',
    name: 'Tắm Muối Biển',
    description: 'Liệu trình tắm muối biển khoáng chất cao cấp kết hợp tinh dầu thơm giúp tẩy tế bào chết, thải độc và tái tạo làn da.',
    price: 520000,
    duration: 90,
    category: 'Chăm Sóc Cơ Thể',
    image: 'https://picsum.photos/seed/spa10/600/400',
    rating: 4.8,
    reviewCount: 68,
    benefits: ['Thải độc cơ thể', 'Tẩy tế bào chết', 'Tái tạo da', 'Khoáng chất thiết yếu'],
    therapists: ['th6', 'th3'],
  },
  {
    id: 'sv11',
    name: 'Chăm Sóc Lông Mày',
    description: 'Dịch vụ tạo hình và chăm sóc lông mày chuyên nghiệp giúp tôn lên vẻ đẹp tự nhiên và làm sắc nét gương mặt.',
    price: 150000,
    duration: 30,
    category: 'Làm Đẹp',
    image: 'https://picsum.photos/seed/spa11/600/400',
    rating: 4.5,
    reviewCount: 201,
    benefits: ['Tôn gương mặt', 'Lông mày tự nhiên', 'Nhanh chóng', 'Chuyên nghiệp'],
    therapists: ['th7', 'th5'],
  },
  {
    id: 'sv12',
    name: 'Massage Cổ Vai Gáy',
    description: 'Liệu pháp massage chuyên sâu vùng cổ, vai và gáy giúp giải phóng căng thẳng, giảm đau nhức do làm việc nhiều giờ.',
    price: 320000,
    duration: 45,
    category: 'Massage',
    image: 'https://picsum.photos/seed/spa12/600/400',
    rating: 4.8,
    reviewCount: 174,
    benefits: ['Giảm đau cổ vai', 'Tăng linh hoạt', 'Giảm đau đầu', 'Thư giãn tức thì'],
    therapists: ['th1', 'th4'],
  },
  {
    id: 'sv13',
    name: 'Body Wrap Thải Độc',
    description: 'Liệu trình bọc cơ thể với hỗn hợp thảo dược đặc biệt giúp thải độc tố, giảm cellulite và cải thiện độ đàn hồi của da.',
    price: 680000,
    duration: 120,
    category: 'Chăm Sóc Cơ Thể',
    image: 'https://picsum.photos/seed/spa13/600/400',
    rating: 4.7,
    reviewCount: 53,
    benefits: ['Thải độc tố', 'Giảm cellulite', 'Tăng đàn hồi', 'Săn chắc da'],
    therapists: ['th6', 'th8'],
  },
  {
    id: 'sv14',
    name: 'Chăm Sóc Móng',
    description: 'Dịch vụ chăm sóc móng tay và móng chân chuyên nghiệp bao gồm cắt, dũa, sơn và dưỡng ẩm giúp móng khỏe đẹp.',
    price: 250000,
    duration: 60,
    category: 'Làm Đẹp',
    image: 'https://picsum.photos/seed/spa14/600/400',
    rating: 4.6,
    reviewCount: 118,
    benefits: ['Móng chắc khỏe', 'Màu sắc bền lâu', 'Dưỡng ẩm móng', 'Thư giãn'],
    therapists: ['th7'],
  },
  {
    id: 'sv15',
    name: 'Scrub Body Trắng Da',
    description: 'Liệu trình tẩy tế bào chết toàn thân với hỗn hợp đường mía, vitamin C và dầu dừa giúp da trắng sáng, mịn màng và rạng rỡ.',
    price: 450000,
    duration: 75,
    category: 'Chăm Sóc Cơ Thể',
    image: 'https://picsum.photos/seed/spa15/600/400',
    rating: 4.8,
    reviewCount: 92,
    benefits: ['Trắng sáng tức thì', 'Tẩy tế bào chết', 'Dưỡng ẩm sâu', 'Mịn màng hoàn hảo'],
    therapists: ['th6', 'th3'],
  },
];

export const products: Product[] = [
  {
    id: 'pr1',
    name: 'Serum Dưỡng Trắng C+',
    description: 'Serum cao cấp với nồng độ vitamin C 20% giúp làm sáng da, mờ thâm nám và bảo vệ da khỏi tác hại của ánh nắng.',
    price: 650000,
    originalPrice: 850000,
    category: 'Dưỡng Da Mặt',
    image: 'https://picsum.photos/seed/spa16/600/400',
    rating: 4.8,
    reviewCount: 89,
    ingredients: 'Vitamin C 20%, Hyaluronic Acid, Niacinamide, Aloe Vera',
    usage: 'Thoa 3-4 giọt lên mặt sạch buổi sáng và tối, sau đó dưỡng ẩm.',
    stock: 45,
  },
  {
    id: 'pr2',
    name: 'Kem Dưỡng Ẩm Ban Đêm',
    description: 'Kem dưỡng ẩm ban đêm giàu dưỡng chất với retinol và collagen giúp phục hồi và tái tạo da trong khi ngủ.',
    price: 450000,
    category: 'Dưỡng Da Mặt',
    image: 'https://picsum.photos/seed/spa17/600/400',
    rating: 4.7,
    reviewCount: 64,
    ingredients: 'Retinol 0.5%, Collagen, Peptide, Shea Butter',
    usage: 'Thoa đều lên mặt và cổ trước khi ngủ sau bước xịt khoáng.',
    stock: 32,
  },
  {
    id: 'pr3',
    name: 'Mặt Nạ Collagen Vàng',
    description: 'Mặt nạ dát vàng 24k kết hợp collagen thủy phân giúp căng da, mờ nhăn và mang lại làn da tươi trẻ sau mỗi lần sử dụng.',
    price: 250000,
    originalPrice: 320000,
    category: 'Mặt Nạ',
    image: 'https://picsum.photos/seed/spa18/600/400',
    rating: 4.9,
    reviewCount: 142,
    ingredients: 'Vàng 24k, Collagen thủy phân, Hyaluronic Acid, Vitamin E',
    usage: 'Đắp lên da mặt sạch 20-30 phút, bóc ra và massage nhẹ nhàng phần tinh chất còn lại.',
    stock: 87,
  },
  {
    id: 'pr4',
    name: 'Toner Cân Bằng Da',
    description: 'Toner cân bằng độ pH da với chiết xuất nước hoa hồng và tràm trà giúp se khít lỗ chân lông và kiểm soát nhờn.',
    price: 320000,
    category: 'Dưỡng Da Mặt',
    image: 'https://picsum.photos/seed/spa19/600/400',
    rating: 4.6,
    reviewCount: 78,
    ingredients: 'Nước hoa hồng, Tràm trà, Niacinamide, Glycerin',
    usage: 'Thấm toner vào bông cotton và thoa nhẹ nhàng lên mặt sau khi rửa mặt.',
    stock: 56,
  },
  {
    id: 'pr5',
    name: 'Tinh Dầu Thư Giãn Lavender',
    description: 'Tinh dầu oải hương nguyên chất 100% giúp thư giãn tinh thần, giảm căng thẳng và cải thiện chất lượng giấc ngủ.',
    price: 180000,
    category: 'Tinh Dầu',
    image: 'https://picsum.photos/seed/spa20/600/400',
    rating: 4.8,
    reviewCount: 203,
    ingredients: 'Tinh dầu oải hương nguyên chất 100%',
    usage: 'Nhỏ 3-5 giọt vào máy khuếch tán hoặc pha với dầu nền để massage.',
    stock: 120,
  },
  {
    id: 'pr6',
    name: 'Kem Chống Nắng SPF50+',
    description: 'Kem chống nắng cao cấp SPF50+/PA++++ bảo vệ toàn diện khỏi tia UVA/UVB, không gây bít tắc lỗ chân lông.',
    price: 380000,
    originalPrice: 450000,
    category: 'Chống Nắng',
    image: 'https://picsum.photos/seed/spa21/600/400',
    rating: 4.7,
    reviewCount: 156,
    ingredients: 'Zinc Oxide, Titanium Dioxide, Vitamin C, Niacinamide',
    usage: 'Thoa đều lên da 20 phút trước khi ra nắng, thoa lại sau 2-3 giờ.',
    stock: 68,
  },
  {
    id: 'pr7',
    name: 'Sữa Tắm Dưỡng Ẩm Hoa Anh Đào',
    description: 'Sữa tắm cao cấp với hương hoa anh đào và chiết xuất collagen giúp dưỡng ẩm, mềm mịn và thơm mát làn da.',
    price: 220000,
    category: 'Chăm Sóc Cơ Thể',
    image: 'https://picsum.photos/seed/spa22/600/400',
    rating: 4.5,
    reviewCount: 94,
    ingredients: 'Collagen, Chiết xuất hoa anh đào, Shea Butter, Vitamin E',
    usage: 'Dùng hàng ngày khi tắm, massage nhẹ và xả sạch với nước.',
    stock: 43,
  },
  {
    id: 'pr8',
    name: 'Kem Dưỡng Tay Chân',
    description: 'Kem dưỡng ẩm chuyên sâu cho tay và chân với bơ shea và dầu dừa giúp mềm mịn vùng da thô ráp, nứt nẻ.',
    price: 150000,
    category: 'Chăm Sóc Cơ Thể',
    image: 'https://picsum.photos/seed/spa23/600/400',
    rating: 4.6,
    reviewCount: 112,
    ingredients: 'Shea Butter, Dầu dừa, Urea 10%, Vitamin E',
    usage: 'Thoa lên tay và chân sau khi tắm, massage cho đến khi thấm hoàn toàn.',
    stock: 75,
  },
  {
    id: 'pr9',
    name: 'Dầu Dưỡng Tóc Argan',
    description: 'Tinh dầu argan Ma-rốc nguyên chất giúp phục hồi tóc hư tổn, tạo độ bóng mượt và bảo vệ tóc khỏi nhiệt độ cao.',
    price: 420000,
    originalPrice: 520000,
    category: 'Chăm Sóc Tóc',
    image: 'https://picsum.photos/seed/spa24/600/400',
    rating: 4.8,
    reviewCount: 87,
    ingredients: 'Dầu argan 100%, Vitamin E, Keratin',
    usage: 'Thoa vài giọt lên tóc ẩm hoặc khô, tránh da đầu.',
    stock: 38,
  },
  {
    id: 'pr10',
    name: 'Muối Tắm Thư Giãn',
    description: 'Muối biển Himalaya kết hợp tinh dầu hoa hồng và oải hương tạo trải nghiệm tắm thư giãn như ở spa tại nhà.',
    price: 195000,
    category: 'Chăm Sóc Cơ Thể',
    image: 'https://picsum.photos/seed/spa25/600/400',
    rating: 4.7,
    reviewCount: 131,
    ingredients: 'Muối Himalaya, Tinh dầu hoa hồng, Tinh dầu oải hương, Dead Sea Salt',
    usage: 'Hòa tan 100g muối vào bồn tắm nước ấm, ngâm 20-30 phút.',
    stock: 92,
  },
  {
    id: 'pr11',
    name: 'Mặt Nạ Đất Sét Xanh',
    description: 'Mặt nạ đất sét xanh Pháp thanh lọc sâu, hút sạch bã nhờn và bụi bẩn, thu nhỏ lỗ chân lông và làm sạch mụn.',
    price: 280000,
    category: 'Mặt Nạ',
    image: 'https://picsum.photos/seed/spa26/600/400',
    rating: 4.6,
    reviewCount: 165,
    ingredients: 'French Green Clay, Kaolin, Tràm trà, Charcoal',
    usage: 'Thoa đều lên mặt tránh vùng mắt, để 15 phút rồi rửa sạch.',
    stock: 54,
  },
  {
    id: 'pr12',
    name: 'Nước Hoa Hồng Dưỡng Da',
    description: 'Nước hoa hồng thuần chay từ cánh hoa hồng hữu cơ giúp cân bằng, làm dịu và cấp ẩm tức thì cho làn da.',
    price: 240000,
    category: 'Dưỡng Da Mặt',
    image: 'https://picsum.photos/seed/spa27/600/400',
    rating: 4.7,
    reviewCount: 98,
    ingredients: 'Nước cất hoa hồng hữu cơ, Glycerin, Panthenol',
    usage: 'Xịt trực tiếp lên da hoặc thấm vào bông cotton thoa đều.',
    stock: 67,
  },
  {
    id: 'pr13',
    name: 'Scrub Cơ Thể Cà Phê',
    description: 'Tẩy da chết cơ thể với bã cà phê Đà Lạt và dầu dừa giúp loại bỏ tế bào chết, chống cellulite và mờ thâm.',
    price: 190000,
    originalPrice: 240000,
    category: 'Chăm Sóc Cơ Thể',
    image: 'https://picsum.photos/seed/spa28/600/400',
    rating: 4.5,
    reviewCount: 176,
    ingredients: 'Bã cà phê Đà Lạt, Dầu dừa, Đường nâu, Vitamin E',
    usage: 'Massage lên da ẩm theo chuyển động tròn, để 5 phút rồi xả sạch.',
    stock: 48,
  },
  {
    id: 'pr14',
    name: 'Tinh Chất Hyaluronic Acid',
    description: 'Serum cấp ẩm tối thượng với 3 loại Hyaluronic Acid trọng lượng phân tử khác nhau giúp da căng mọng, ẩm mượt suốt 24 giờ.',
    price: 580000,
    category: 'Dưỡng Da Mặt',
    image: 'https://picsum.photos/seed/spa29/600/400',
    rating: 4.9,
    reviewCount: 73,
    ingredients: 'Hyaluronic Acid 3 kích thước, B5, Ceramide',
    usage: 'Thoa 4-5 giọt lên da sạch buổi sáng và tối, vỗ nhẹ cho thấm.',
    stock: 29,
  },
  {
    id: 'pr15',
    name: 'Kem Mắt Trẻ Hóa',
    description: 'Kem dưỡng vùng mắt cao cấp với caffeine và retinol giúp giảm thâm quầng, bọng mắt và nếp nhăn vùng mắt.',
    price: 480000,
    originalPrice: 580000,
    category: 'Dưỡng Da Mặt',
    image: 'https://picsum.photos/seed/spa30/600/400',
    rating: 4.7,
    reviewCount: 52,
    ingredients: 'Caffeine 3%, Retinol 0.3%, Peptide, Vitamin K',
    usage: 'Thoa một lượng nhỏ xung quanh vùng mắt buổi sáng và tối.',
    stock: 21,
  },
  {
    id: 'pr16',
    name: 'Dầu Massage Thư Giãn',
    description: 'Hỗn hợp tinh dầu nguyên chất gồm oải hương, bạc hà và cam bergamot tạo ra liệu pháp massage thư giãn hoàn hảo.',
    price: 260000,
    category: 'Tinh Dầu',
    image: 'https://picsum.photos/seed/spa31/600/400',
    rating: 4.8,
    reviewCount: 119,
    ingredients: 'Dầu hạt nho, Tinh dầu oải hương, Tinh dầu bạc hà, Tinh dầu bergamot',
    usage: 'Thoa lên da, massage theo chuyển động tròn và nhẹ nhàng.',
    stock: 61,
  },
  {
    id: 'pr17',
    name: 'Gel Rửa Mặt Dịu Nhẹ',
    description: 'Sữa rửa mặt không chứa sulfate với pH cân bằng, làm sạch nhẹ nhàng mà không làm khô da hay phá vỡ hàng rào bảo vệ da.',
    price: 195000,
    category: 'Dưỡng Da Mặt',
    image: 'https://picsum.photos/seed/spa32/600/400',
    rating: 4.6,
    reviewCount: 144,
    ingredients: 'Glucoside Caprylyl, Aloe Vera, Panthenol, Allantoin',
    usage: 'Dùng ngày 2 lần sáng và tối, lấy lượng vừa đủ massage lên da ướt và xả sạch.',
    stock: 83,
  },
  {
    id: 'pr18',
    name: 'Bộ Chăm Sóc Da Cơ Bản',
    description: 'Bộ 4 sản phẩm chăm sóc da cơ bản gồm sữa rửa mặt, toner, serum và kem dưỡng - đầy đủ quy trình skincare hàng ngày.',
    price: 950000,
    originalPrice: 1200000,
    category: 'Bộ Sản Phẩm',
    image: 'https://picsum.photos/seed/spa33/600/400',
    rating: 4.9,
    reviewCount: 38,
    ingredients: 'Xem từng sản phẩm trong bộ',
    usage: 'Dùng theo thứ tự: sữa rửa mặt → toner → serum → kem dưỡng.',
    stock: 15,
  },
  {
    id: 'pr19',
    name: 'Xịt Khoáng Dưỡng Da',
    description: 'Xịt khoáng chứa khoáng chất từ biển sâu và chiết xuất lô hội giúp cấp ẩm tức thì, làm dịu da và cố định lớp trang điểm.',
    price: 175000,
    category: 'Dưỡng Da Mặt',
    image: 'https://picsum.photos/seed/spa34/600/400',
    rating: 4.5,
    reviewCount: 187,
    ingredients: 'Khoáng chất biển sâu, Aloe Vera, Chamomile, Glycerin',
    usage: 'Xịt cách mặt 20-30cm, dùng bất cứ lúc nào da cần bổ sung độ ẩm.',
    stock: 109,
  },
  {
    id: 'pr20',
    name: 'Tinh Dầu Hoa Hồng Bulgaria',
    description: 'Tinh dầu hoa hồng Bulgaria cao cấp với hương thơm quý phái, có tác dụng dưỡng ẩm, chống lão hóa và cân bằng tâm trạng.',
    price: 890000,
    originalPrice: 1100000,
    category: 'Tinh Dầu',
    image: 'https://picsum.photos/seed/spa35/600/400',
    rating: 5.0,
    reviewCount: 26,
    ingredients: 'Tinh dầu hoa hồng Damascus 100% Bulgaria',
    usage: 'Pha loãng 2% với dầu nền để massage hoặc dùng trong máy khuếch tán.',
    stock: 12,
  },
];

export const therapists: Therapist[] = [
  {
    id: 'th1',
    name: 'Nguyễn Thị Lan',
    specialty: 'Massage Trị Liệu',
    bio: 'Chuyên viên massage với hơn 8 năm kinh nghiệm, chuyên về các liệu pháp massage thư giãn và trị liệu. Được đào tạo tại Thái Lan và Nhật Bản.',
    image: 'https://picsum.photos/seed/th1/400/400',
    rating: 4.9,
    experience: 8,
    services: ['sv1', 'sv4', 'sv6', 'sv12'],
  },
  {
    id: 'th2',
    name: 'Trần Thị Hoa',
    specialty: 'Chăm Sóc Da',
    bio: 'Chuyên gia thẩm mỹ da liễu với chứng chỉ quốc tế, 6 năm kinh nghiệm trong lĩnh vực chăm sóc da và trị liệu sắc đẹp.',
    image: 'https://picsum.photos/seed/th2/400/400',
    rating: 4.8,
    experience: 6,
    services: ['sv2', 'sv5', 'sv7', 'sv8'],
  },
  {
    id: 'th3',
    name: 'Lê Thị Mai',
    specialty: 'Massage Đá Nóng',
    bio: 'Chuyên viên massage đá nóng được chứng nhận, có 5 năm kinh nghiệm ứng dụng liệu pháp nhiệt đá bazan trong điều trị đau cơ và thư giãn.',
    image: 'https://picsum.photos/seed/th3/400/400',
    rating: 4.7,
    experience: 5,
    services: ['sv4', 'sv10', 'sv15'],
  },
  {
    id: 'th4',
    name: 'Phạm Thị Thu',
    specialty: 'Massage Thái Cổ Truyền',
    bio: 'Được đào tạo trực tiếp tại Chiang Mai, Thái Lan, chuyên viên có 7 năm kinh nghiệm trong massage Thái truyền thống và bấm huyệt.',
    image: 'https://picsum.photos/seed/th4/400/400',
    rating: 4.9,
    experience: 7,
    services: ['sv6', 'sv9', 'sv12'],
  },
  {
    id: 'th5',
    name: 'Hoàng Thị Nga',
    specialty: 'Facial & Trẻ Hóa Da',
    bio: 'Chuyên gia facial với 9 năm kinh nghiệm, chứng chỉ từ Hàn Quốc về công nghệ trẻ hóa da, chuyên điều trị nám và chống lão hóa.',
    image: 'https://picsum.photos/seed/th5/400/400',
    rating: 5.0,
    experience: 9,
    services: ['sv2', 'sv5', 'sv8', 'sv11'],
  },
  {
    id: 'th6',
    name: 'Đỗ Thị Bích',
    specialty: 'Chăm Sóc Cơ Thể',
    bio: 'Chuyên viên body treatment với 6 năm kinh nghiệm, chuyên về các liệu pháp dưỡng trắng, tắm dưỡng và body wrap thải độc.',
    image: 'https://picsum.photos/seed/th6/400/400',
    rating: 4.8,
    experience: 6,
    services: ['sv3', 'sv7', 'sv10', 'sv13', 'sv15'],
  },
  {
    id: 'th7',
    name: 'Vũ Thị Linh',
    specialty: 'Nail & Làm Đẹp',
    bio: 'Chuyên gia nail art và làm đẹp với 4 năm kinh nghiệm, được đào tạo tại Hàn Quốc về kỹ thuật nail và chăm sóc lông mày.',
    image: 'https://picsum.photos/seed/th7/400/400',
    rating: 4.7,
    experience: 4,
    services: ['sv11', 'sv14'],
  },
  {
    id: 'th8',
    name: 'Bùi Thị Hằng',
    specialty: 'Phản Xạ Học',
    bio: 'Chuyên gia phản xạ học với 10 năm kinh nghiệm, chứng chỉ quốc tế về massage bàn chân theo phương pháp phản xạ học và y học cổ truyền.',
    image: 'https://picsum.photos/seed/th8/400/400',
    rating: 4.9,
    experience: 10,
    services: ['sv9', 'sv13'],
  },
];

export const reviews: Review[] = [
  {
    id: 'rv1',
    customerName: 'Nguyễn Thị Minh',
    rating: 5,
    comment: 'Dịch vụ massage tuyệt vời! Chị Lan rất chuyên nghiệp và tay nghề cao. Cảm giác thư giãn hoàn toàn sau buổi massage. Sẽ quay lại nhiều lần nữa.',
    date: '2024-02-15',
    serviceId: 'sv1',
  },
  {
    id: 'rv2',
    customerName: 'Trần Văn Hùng',
    rating: 5,
    comment: 'Không gian spa rất sang trọng và sạch sẽ. Dịch vụ facial của chị Nga làm da mình căng mịn hẳn. Rất đáng tiền!',
    date: '2024-02-18',
    serviceId: 'sv8',
  },
  {
    id: 'rv3',
    customerName: 'Lê Thị Phương',
    rating: 4,
    comment: 'Tắm dưỡng trắng da thực sự hiệu quả. Sau một buổi da đã thấy sáng và mịn hơn nhiều. Nhân viên thân thiện và nhiệt tình.',
    date: '2024-02-20',
    serviceId: 'sv3',
  },
  {
    id: 'rv4',
    customerName: 'Phạm Thị Lan',
    rating: 5,
    comment: 'Massage đá nóng là trải nghiệm tuyệt vời nhất tôi từng có. Cơ thể thư giãn hoàn toàn, cảm giác như được tái sinh. Cảm ơn Lotus Spa!',
    date: '2024-02-22',
    serviceId: 'sv4',
  },
  {
    id: 'rv5',
    customerName: 'Hoàng Văn Minh',
    rating: 4,
    comment: 'Massage Thái cổ truyền rất chuyên nghiệp. Chị Thu có kỹ thuật tốt, giúp mình giảm đau lưng đáng kể. Sẽ đặt lịch thường xuyên.',
    date: '2024-02-25',
    serviceId: 'sv6',
  },
  {
    id: 'rv6',
    customerName: 'Vũ Thị Hà',
    rating: 5,
    comment: 'Serum vitamin C tuyệt vời! Dùng được 2 tuần da đã sáng lên rõ rệt, thâm mụn mờ đi nhiều. Đóng gói đẹp, giao hàng nhanh.',
    date: '2024-02-28',
    productId: 'pr1',
  },
  {
    id: 'rv7',
    customerName: 'Đặng Thị Nhi',
    rating: 5,
    comment: 'Không gian spa cực kỳ yên tĩnh và thư giãn. Body wrap thải độc làm mình cảm thấy nhẹ nhàng và tươi mới hơn hẳn. Nhất định sẽ quay lại!',
    date: '2024-03-01',
    serviceId: 'sv13',
  },
  {
    id: 'rv8',
    customerName: 'Bùi Thị Thảo',
    rating: 4,
    comment: 'Massage bàn chân phản xạ thực sự giúp tôi ngủ ngon hơn sau khi sử dụng. Chị Hằng rất có kinh nghiệm và am hiểu phản xạ học.',
    date: '2024-03-03',
    serviceId: 'sv9',
  },
  {
    id: 'rv9',
    customerName: 'Ngô Thị Kim',
    rating: 5,
    comment: 'Mặt nạ collagen vàng xịn thật sự! Dùng xong da căng mịn như da em bé. Giá cả hợp lý, sẽ mua thêm nhiều lần nữa.',
    date: '2024-03-05',
    productId: 'pr3',
  },
  {
    id: 'rv10',
    customerName: 'Lý Thị Mai',
    rating: 5,
    comment: 'Tổng thể dịch vụ của Lotus Spa rất xuất sắc. Từ lúc bước vào đến khi ra về đều cảm thấy được chăm sóc chu đáo. Spa tốt nhất tôi từng đến!',
    date: '2024-03-08',
  },
];

export const promotions: Promotion[] = [
  {
    id: 'pm1',
    title: 'Ưu Đãi Chào Xuân 2024',
    description: 'Giảm 30% tất cả dịch vụ massage và chăm sóc da trong tháng 3. Áp dụng cho khách hàng đặt lịch trước 3 ngày.',
    discount: 30,
    validUntil: '2024-03-31',
    image: 'https://picsum.photos/seed/pm1/600/400',
    code: 'XUÂN2024',
  },
  {
    id: 'pm2',
    title: 'Gói Đôi Lãng Mạn',
    description: 'Đặt 2 chỗ bất kỳ dịch vụ nào, giảm ngay 20%. Hoàn hảo cho các cặp đôi muốn trải nghiệm spa cùng nhau.',
    discount: 20,
    validUntil: '2024-04-15',
    image: 'https://picsum.photos/seed/pm2/600/400',
    code: 'DOILANMAN',
  },
  {
    id: 'pm3',
    title: 'Thành Viên Mới - Ưu Đãi Đặc Biệt',
    description: 'Đăng ký thành viên mới nhận ngay voucher giảm 15% cho lần đầu tiên sử dụng dịch vụ tại Lotus Spa.',
    discount: 15,
    validUntil: '2024-12-31',
    image: 'https://picsum.photos/seed/pm3/600/400',
    code: 'NEWMEMBER',
  },
  {
    id: 'pm4',
    title: 'Mua Sản Phẩm Tặng Voucher',
    description: 'Mua sản phẩm từ 500.000đ trở lên nhận voucher giảm 10% cho dịch vụ tiếp theo. Không giới hạn số lần sử dụng.',
    discount: 10,
    validUntil: '2024-05-31',
    image: 'https://picsum.photos/seed/pm4/600/400',
    code: 'MUASANPHAM',
  },
];

export const appointments: Appointment[] = [
  {
    id: 'ap1',
    serviceId: 'sv1',
    serviceName: 'Massage Thư Giãn Toàn Thân',
    therapistId: 'th1',
    therapistName: 'Nguyễn Thị Lan',
    date: '2024-03-15',
    time: '10:00',
    price: 450000,
    status: 'confirmed',
    notes: 'Tập trung vùng lưng và vai',
  },
  {
    id: 'ap2',
    serviceId: 'sv8',
    serviceName: 'Facial Trẻ Hóa Da',
    therapistId: 'th5',
    therapistName: 'Hoàng Thị Nga',
    date: '2024-03-20',
    time: '14:00',
    price: 850000,
    status: 'pending',
  },
  {
    id: 'ap3',
    serviceId: 'sv4',
    serviceName: 'Massage Đá Nóng',
    therapistId: 'th3',
    therapistName: 'Lê Thị Mai',
    date: '2024-02-28',
    time: '11:00',
    price: 550000,
    status: 'completed',
    notes: 'Lần đầu thử massage đá nóng',
  },
  {
    id: 'ap4',
    serviceId: 'sv3',
    serviceName: 'Tắm Dưỡng Trắng Da',
    therapistId: 'th6',
    therapistName: 'Đỗ Thị Bích',
    date: '2024-02-10',
    time: '15:00',
    price: 600000,
    status: 'completed',
  },
  {
    id: 'ap5',
    serviceId: 'sv9',
    serviceName: 'Massage Bàn Chân Phản Xạ',
    therapistId: 'th8',
    therapistName: 'Bùi Thị Hằng',
    date: '2024-03-25',
    time: '09:00',
    price: 280000,
    status: 'cancelled',
    notes: 'Hủy do bận việc đột xuất',
  },
];
